In [41]:
import pandas as pd

In [42]:
def removeDupes(x):
    final = []
    lst = x.split(",")
    for i in lst:
        y = i.strip()
        z = int(len(y)/2)

        if y[:z] == y[z:]:
            final.append(y[z:])
        else:
            final.append(y)
    return ','.join(final)

In [56]:
def find_prequel(w):
    for j in w.split(","):
        for i in j.split(":"):
            if i == 'Prequel':
                return 1
    return 0

def find_hentai(w):
    for i in w.split(" "):
        if i == 'Hentai':
            return 1
    return 0

In [43]:
dirty_anime_path = 'C:/Users/dguer/Desktop/Coding/Proyectos/AniMatch/backend/notebooks/scraping_data/dirty_anime.csv'

In [61]:
DATA_PATH = "C:/Users/dguer/Desktop/Coding/Proyectos/AniMatch/backend/apis/data"

In [62]:
def pipeData4Filter(dirty_anime_path):
    df = pd.read_csv(dirty_anime_path)
    df.drop(['Unnamed: 0'], axis=1, inplace=True)

    df.Licensors = df.Licensors.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
    df.Licensors = df.Licensors.apply(removeDupes)

    df.Source = df.Source.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
    df.Source = df.Source.apply(removeDupes)

    df.Studios = df.Studios.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
    df.Studios = df.Studios.apply(removeDupes)
    
    df.Genres = df.Genres.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
    df.Genres = df.Genres.apply(removeDupes)

    df.Related_content = df.Related_content.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
    df.Related_content = df.Related_content.apply(removeDupes)

    df['Prequel'] = 0
    df['Prequel'] = df['Related_content'].apply(find_prequel)
    df['Hentai'] = df['Genres'].apply(find_hentai)
    df[df['Hentai'] == 1]['Title']

    jojo_df = df[['index', 'Hentai', 'Prequel']]
    jojo_df.columns = ['Id', 'Hentai', 'Prequel']
    jojo_df = jojo_df.drop_duplicates()

    anime_df = pd.read_csv(DATA_PATH+"/data4filter.csv")
    anime_df.set_index('Id')

    final_df = anime_df.merge(jojo_df, how="left", on="Id")
    final_df.to_csv(DATA_PATH+"/m_data4filter.csv", index=False)

In [ ]:
df = pd.read_csv("C:/Users/dguer/Desktop/Coding/Proyectos/AniMatch/backend/notebooks/scraping_data/dirty_anime.csv")
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.head(5)

In [47]:
word = "Themes, ParodyParody,         SchoolSchool"

In [48]:
removeDupes(word)

'Themes,Parody,School'

In [49]:
df.Licensors = df.Licensors.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Licensors = df.Licensors.apply(removeDupes)
df.Licensors

0                 Studios,Tokyo Movie Shinsha
1                         Genres,Drama,Sports
2        Genres,Adventure,Drama,Slice of Life
3                         Theme,Combat Sports
4                Genres,Award Winning,Fantasy
                         ...
70767                            Source,Manga
70768              Studios,Studio Eight Color
70769                            Genre,Sports
70770                        Theme,Historical
70771                    Themes,Parody,School
Name: Licensors, Length: 70772, dtype: object

In [50]:
df.Studios = df.Studios.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Studios = df.Studios.apply(removeDupes)
df.Studios

0                  Source,Manga
1             Theme,Team Sports
2        Duration,1 hr. 21 min.
3           Demographic,Shounen
4                   Theme,Music
                  ...
70767          Duration,Unknown
70768          Source,Web manga
70769         Theme,Team Sports
70770          Duration,Unknown
70771          Duration,Unknown
Name: Studios, Length: 70772, dtype: object

In [51]:
df.Source = df.Source.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Source = df.Source.apply(removeDupes)
df.Source

0                     Genres,Drama,Sports
1                      Demographic,Shoujo
2                     Rating,G - All Ages
3                        Duration,47 min.
4                        Demographic,Kids
                       ...
70767                         Rating,None
70768                        Genre,Comedy
70769                    Duration,Unknown
70770                         Rating,None
70771    Rating,PG-13 - Teens 13 or older
Name: Source, Length: 70772, dtype: object

In [52]:
df.Genres = df.Genres.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Genres = df.Genres.apply(removeDupes)
df.Genres

0                                        Theme,Team Sports
1                                    Duration,1 hr. 5 min.
2        Score,5.841 (scored by 330330 users)\r      \r...
3                         Rating,PG-13 - Teens 13 or older
4                                         Duration,27 min.
                               ...
70767    Score,N/A1 (scored by - users)\r      \r1\r   ...
70768                            Themes,Pets,Reincarnation
70769                                          Rating,None
70770    Score,N/A1 (scored by - users)\r      \r1\r   ...
70771    Score,N/A1 (scored by - users)\r      \r1\r   ...
Name: Genres, Length: 70772, dtype: object

In [ ]:
df.Related_content = df.Related_content.apply(lambda x: str(x).strip().replace("\n", "").replace("\t", ""))
df.Related_content = df.Related_content.apply(removeDupes)
df.Related_content

In [20]:
x = "Prequel:: /anime/45335/Bing_Ji_Chaoren_Kuaidi_Xia"
x

'Prequel:: /anime/45335/Bing_Ji_Chaoren_Kuaidi_Xia'

In [57]:
anime_df = pd.read_csv(DATA_PATH+"/data4filter.csv")
anime_df.head(3)

   Id  Score  Episodes  Min_Duration  Year
0   1   8.78        26          24.0  1998
1   5   8.39         1         115.0  2001
2   6   8.24        26          24.0  1998

In [58]:
anime_df.set_index('Id')

       Score  Episodes  Min_Duration  Year
Id
1       8.78        26          24.0  1998
5       8.39         1         115.0  2001
6       8.24        26          24.0  1998
7       7.27        26          25.0  2002
8       6.98        52          23.0  2004
...      ...       ...           ...   ...
47778    NaN      1000           0.0  2021
48438    NaN         3           0.0  2021
48456   6.52         1          23.0  2021
48483    NaN      1000           0.0  2021
48488    NaN      1000           0.0  2021

[6680 rows x 4 columns]

In [33]:
final_df = anime_df.merge(jojo_df, how="left", on="Id")
final_df

         Id  Score  Episodes  Min_Duration  Year  Hentai  Prequel
0         1   8.78        26          24.0  1998     0.0      0.0
1         5   8.39         1         115.0  2001     0.0      0.0
2         6   8.24        26          24.0  1998     0.0      0.0
3         7   7.27        26          25.0  2002     0.0      0.0
4         8   6.98        52          23.0  2004     0.0      0.0
...     ...    ...       ...           ...   ...     ...      ...
6689  47778    NaN      1000           0.0  2021     0.0      1.0
6690  48438    NaN         3           0.0  2021     0.0      0.0
6691  48456   6.52         1          23.0  2021     0.0      0.0
6692  48483    NaN      1000           0.0  2021     0.0      0.0
6693  48488    NaN      1000           0.0  2021     0.0      1.0

[6694 rows x 7 columns]

In [34]:
final_df[final_df['Id'] == 35247]

         Id  Score  Episodes  Min_Duration  Year  Hentai  Prequel
5463  35247   8.93         7          22.0  2017     0.0      0.0

In [38]:
jojo_df = jojo_df.sort_values("Id").reset_index()
jojo_df = jojo_df.drop(['level_0', 'index'], axis=1)
jojo_df

          Id  Hentai  Prequel
0          1       0        0
1          5       0        0
2          6       0        0
3          7       0        0
4          8       0        0
...      ...     ...      ...
17709  58535       0        0
17710  58563       0        0
17711  58564       0        0
17712  58569       0        1
17713  58572       0        1

[17714 rows x 3 columns]